services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: practica3_mosquitto
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - ./mosquitto-docker-compose/config/:/mosquitto/config/
      - ./mosquitto-docker-compose/log/:/mosquitto/log/
      - ./mosquitto-docker-compose/data/:/mosquitto/data/
    networks:
      - practica3_network

  python_server:
    image: python:3.14.5
    container_name: python_server
    # Keep alive
    tty: true
    stdin_open: true
    volumes:
      - ./raw:/raw
      - ./wisdm-dataset:/wisdm-dataset
      - ./python_scripts:/python_scripts
    # Ejecucion manual
    #command: "pip install paho-mqtt && /bin/bash"
    # TODO: Uasr el comando de ejecucion desatendida
    #command: "pip install paho-mqtt && python /python_scripts/publicador.py"
    networks:
      - practica3_network
    depends_on:
      - mosquitto

  zookeeper:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - practica3_network
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - practica3_network
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.1.0
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - practica3_network
    volumes:
      - ./kafka/jars/:/etc/kafka-connect/jars
    depends_on:
      - kafka

  mongo-db:
    image: mongo:4.0.5
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - practica3_network
    command: --bind_ip_all --smallfiles

  mongoclient:
    image: mongoclient/mongoclient:2.2.0
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongo-db
    ports:
      - 3000:3000
    environment:
      MONGO_URL: "mongodb://mongo-db:27017"
      PORT: 3000
    networks:
      - practica3_network
    expose:
      - "3000"

networks:
  practica3_network:
    name: practica3_network
    driver: bridge
    external: true
